base_images:
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.13"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: interconnect-amp-interop-aws
  cron: 0 1 * * 1
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: aws.interop.ccitredhat.com
      OPERATORS: |
        [
            {"name": "interconnect-operator", "source": "redhat-operators", "channel": "!default", "install_namespace": "interconnect", "target_namespaces": "interconnect"}
        ]
      SPOT_INSTANCES: "true"
    test:
    - ref: install-operators
    workflow: ipi-aws
zz_generated_metadata:
  branch: interconnect-interconnect-operator-4.13-candidate
  org: interconnect-qe
  repo: interconnect-tests
